# pnpm-workspace.yaml  (repo root)
packages:
  # every leaf workspace lives here
  - "packages/**"          # cli, config, host, lambda, observables, utils
  - ".papi/descriptors"    # 👈 new line
  - "example-apps/*"
  - "integration-tests/*"
  - "scripts/*"

# TODO! inspect each of them & remove ones not needed 
# (probably everything besides `better-sqlite3`, the rest were copied from papi repo)
# 
# optional: skip rebuilding “native” deps unless their own sources change
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - node-hid
  - sqlite3
  - better-sqlite3
  - usb
